// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xslhffvpefkffhrniwmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzbGhmZnZwZWZrZmZocm5pd215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDkxNzEsImV4cCI6MjA2MDYyNTE3MX0.3ASlPKsnMAqKU1TqoKg3h90Tua9sg6KuFAbc__BB1JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);